name: test

on:
  pull_request:
  push:
    branches: [master]
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
    steps:
      # Prepare environment
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry

      # Install specific alternate python versions required by hooks
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
          cache: poetry

      # Run all tests
      - run: poetry install
      - run: poetry run pytest --color yes
        env:
          SELECTED_ODOO_VERSIONS: 18.0
